name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4  # Update to version that uses Node.js 20uses: actions/checkout@v4  # Update to version that uses Node.js 20
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t svfagsrs/project2-app .
      - name: Publish image to docker hub
        run: docker push svfagsrs/project2-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from docker hub
        run: docker pull svfagsrs/project2-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container || true
      - name: Run docker container
        run: docker run -d -p 4000:4000 --name nodejs-app-container svfagsrs/project2-app:latest

